version = "1.0"
robust = "normal"

[models]
wpl = "./models/wpl"
oml = "./models/oml"
[topology]
sources = "./topology/sources"
sinks = "./topology/sinks"

[performance]
rate_limit_rps = 10000
parse_workers = 2

[rescue]
path = "./data/rescue"

[log_conf]
#level = "warn,ctrl=trace,dfx=info,data=debug"
level = "warn,ctrl=debug,dfx=info,data=warn"
output = "File"

[log_conf.file]
path = "./data/logs"

[stat]

[[stat.pick]]
key = "pick_stat"
target = "*"

[[stat.parse]]
key = "parse_stat"
target = "*"

[[stat.sink]]
key = "sink_stat"
target = "*"

[admin_api]
enabled = true
bind = "0.0.0.0:19090"
request_timeout_ms = 15000
max_body_bytes = 4096

[admin_api.auth]
mode = "bearer_token"
token_file = ".run/admin_api.token"

[admin_api.tls]
enabled = false

[project_remote]
enabled = false
repo = "http://gitea:3000/gitea/project_root.git"
init_version = "1.0.0"