{
 "title": "wparse view",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Parse Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(increase(wparse_parse_success[1m]))/sum(increase(wparse_receive_data[1m])) \n",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Parse the total number of all logs rate /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(wparse_parse_all{parse=\"parse\"}[1m]))",
     "legendFormat": "parse"
    }
   ]
  },
  { "title": "count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Parse Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(wparse_parse_success)/sum(wparse_receive_data)",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Parse the total number of all logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(wparse_parse_all {parse=\"parse\"})",
     "legendFormat": "parse"
    }
   ]
  },
  {
   "title": "Total count of successfully parsed log entries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(wparse_parse_success)by(rule_name)",
     "legendFormat": "{{rule_name}}"
    }
   ]
  },
  {
   "title": "Log count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(wparse_receive_data)by(key)",
     "legendFormat": "{{key}}"
    }
   ]
  }
 ]
}