version = "2.0"

[sink_group]
name = "all"
oml = ["/*"]
batch_timeout_ms=5000
parallel = 1
[[sink_group.sinks]]
name = "database"
connect = "postgres_sink"
[sink_group.sinks.params]
endpoint = "localhost:5432"
username = "postgres"
password = "123456"
database = "wparse"
table = "nginx_logs"
columns = ["sip", "timestamp", "http/request", "status", "size", "referer", "http/agent"]
batch_size = 100000
