version = "2.0"

[sink_group]
name = "miss"
oml = []
batch_size = 10
[[sink_group.sinks]]
connect = "file_raw_sink"
params = {  file = "miss.dat" , sync = "true"  }
[sink_group.sinks.expect]
# 当前 miss 汇总约为输入的 6 倍，保留少量波动空间。
ratio = 6.00
tol   = 0.20
