service:
  flush: 1
  daemon: no
  log_level: info
  http_server: true
  http_listen: 0.0.0.0
  http_port: 2020
  hot_reload: true
pipeline:
  inputs:
    - name: tail
      path: ./test-logs/*.dat
      path_key: filename
      tag: dummy.nginx

    - name: tail
      path: /host/var/log/nginx/access.log
      path_key: filename
      tag: prod.nginx

    - name: tcp
      listen: 0.0.0.0
      port: 5170
      chunk_size: 32
      buffer_size: 64
      format: none

  outputs:
    - name: stdout
      match: "prod.nginx"

    - name: tcp
      match: "*"
      host: host.docker.internal
      port: 19002
      format: json_lines

    - name: tcp
      match: "prod.nginx"
      host: host.docker.internal
      port: 19003
      format: json_lines