[[connectors]]
allow_override = ["addr", "port", "protocol", "tcp_recv_bytes", "udp_recv_buffer", "header_mode", "fast_strip"]
id = "syslog_src"
type = "syslog"

[connectors.params]
addr = "0.0.0.0"
fast_strip = false
header_mode = "skip"
port = 514
protocol = "udp"
tcp_recv_bytes = 10485760
udp_recv_buffer = 8388608
